// v1.0 устаревшие типы для обратной совместимости
export type KakeboCategoryLegacy = 'LIFE' | 'CULTURE' | 'EXTRA' | 'UNEXPECTED'

export interface KakeboEntry {
  id: string
  date: string
  categoryId?: string | null
  category?: {
    id: string
    name: string
    type: 'SYSTEM' | 'CUSTOM'
    icon?: string | null
    color?: string | null
  } | null
  categoryOld?: KakeboCategoryLegacy // для совместимости при миграции
  description: string
  amount: number
  isNecessary: boolean
  isAutoGenerated?: boolean
}

export interface KakeboSettings {
  monthLimit: number | null
  income?: number | null
}

export interface KakeboSummary {
  totalSpent: number
  daysInMonth: number
  daysWithEntries: number
  byCategory: Record<string, number>
}

export interface KakeboMonthData {
  settings: KakeboSettings
  entries: KakeboEntry[]
  summary: KakeboSummary
}

export interface KakeboReflection {
  id?: string
  year: number
  month: number
  unnecessarySpent?: number
  moneyAtStart?: number
  plannedToSave?: number
  actuallySaved?: number
  improvements?: string
}

// v2.0 новые типы

export interface KakeboCategory {
  id: string
  name: string
  type: 'SYSTEM' | 'CUSTOM'
  parentId?: string | null
  isFixed?: boolean
  isEssential?: boolean
  icon?: string | null
  color?: string | null
  order?: number
  children?: KakeboCategory[]
}

export interface KakeboMonthlyGoal {
  id?: string
  year: number
  month: number
  promise?: string
  targetSave: number
  achieved?: boolean
  createdAt?: string
  updatedAt?: string
}

export interface KakeboFixedExpense {
  id?: string
  categoryId: string
  category?: {
    id: string
    name: string
    icon?: string | null
  } | null
  description: string
  amount: number
  dayOfMonth: number
  isActive?: boolean
  startDate?: string | null
  endDate?: string | null
  notes?: string | null
}

export interface KakeboMonthlyBudget {
  id?: string
  year: number
  month: number
  income: number
}

export interface KakeboBudgetCalculation {
  income: number
  fixedExpenses: number
  savingGoal: number
  remaining: number
  spentOnVariable: number
  remainingToSpend: number
  isOverBudget: boolean
}
